### PR TITLE
Feature: PT Translation

### PR DESCRIPTION
**Pull request by pedro-hdias**
This pull request have the objetive to add portuguese translation to add-on total commander.
On this pull request have files of documentation and the translation.
Also, this pull request give open the way to other people make adaptations to portuguese europian and anyone variant from portuguese.

### CODE REVIEW

**Comment by jawhien** [comment]
@pedro-hdias 
Hello. Thanks for your work :)
Before Merge  this pull request, we need to revert the changes to the .gitignore file and also remove the *.mo binaries, as the translation is compiled at build time and the binaries should not be present in the repository.
Also, the documentation must be in markdown format, for correct display on GitHub and subsequent compilation. *.html files are not included in the repository :(

**Comment by pedro-hdias** [comment]
Hello.Ok, i’ll try revert the .gitignore. I ahd thought did it but... I think that i forgot it, sorry.About the html’s file, does it need have in the repositor or not? I have doubts about that.I’ll also remove the file.mo. I didn’t know that the translate was compiled when compiles the add-on.Thank you for your observation. Enviado do Email para Windows De: Eugene PoplavskyEnviado:segunda-feira, 13 de fevereiro de 2023 09:02Para: jawhien/extendedTotalCmdCc:pedro-hdias; MentionAssunto: Re: [jawhien/extendedTotalCmd] Feature: PT Translation (PR ***@***.*** Thanks for your work :)Before Merge this pull request, we need to revert the changes to the .gitignore file and also remove the *.mo binaries, as the translation is compiled at build time and the binaries should not be present in the repository.Also, the documentation must be in markdown format, for correct display on GitHub and subsequent compilation. *.html files are not included in the repository :(—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jawhien** [comment]
Hello. It's okay, mo files and manifests are created at build, so they are added to .gitignore.
The html files are also created on build. they are also added to .gitignore.
documentation requires markdown files.
You can see it in the English documentation in addon/doc/en/readme.md

**Comment by pedro-hdias** [comment]
Hello. It's ok, now I get all. I'll make the changes in this next days. Sorry for late answer but I had a travel and I didn't get use my compuuter. Wait me for more news. Thanks a lot again for your help!

**Comment by pedro-hdias** [comment]
Hello @jawhien . I believe that I get fixe all isues that you reported to me. Please, make a check and don't exite in talk to me about all things that you find.

**Comment by jawhien** [comment]
@pedro-hdias 
Hello. Everything looks good, however, if possible, remove the *.ini and *.mo files.
Perhaps these files will be automatically deleted during the merge.

Excuse me, I'll need a little more time to go through all the details as I'm currently in the hospital with a serious hand injury.
So I'll take a look over the weekend and do a merge if possible.

**Comment by pedro-hdias** [comment]
# Hello @jawhien!
I hope that on this moment you're be great and have healed from your hand lesion.
I'll remove it but, the file.ini that's on the localle/pt, localle/pt-br and localle/pt_pt folders is required to the about informations of your add-on be translated to portuguese. Without this files, when I try see informations about your add-on on NVDA, all is displaied in english.
But, the file .mo, i guess that I been removed, if not, sorry!
I wait news about you shortly and if I may mantain files.ini that's into localle folder, it's really important.

**Comment by pedro-hdias** [comment]
Hi @jawhien , How's going? I hope that you're good again.
I did the deletions as you asked but, the files *.ini be really important to exib in poprtuguese the about informations of your add-on on Manage add-ons... Maybe you think about remove the restriction of .ini's files from the .gitignore, please.

**Comment by pedro-hdias** [comment]
rather than exib, I wanted says: to show!

**Comment by jawhien** [comment]
@pedro-hdias 
Hello. Thank you. I couldn't work properly for more than two months because of this, but now I'm relatively fine.
Don't worry about the manifest.ini files, they are created when executing scons from *.po translation files.
In any case, I will check everything after the merge, and if something is wrong, I will fix it.
Thanks again for your work! :))

**Pull request merged**
